version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 1000
  groups:
    AWSSDK:
      patterns:
        - "AWSSDK.*"
  ignore:
    # Particular.Analyzers updates are distributed via RepoStandards
    - dependency-name: "Particular.Analyzers"
    # Changing these 3 dependencies affects the .NET SDK and Visual Studio versions we support 
    # These types of updates should be more intentional than an automated update
    - dependency-name: "Microsoft.Build.Utilities.Core"
    - dependency-name: "Microsoft.CodeAnalysis.CSharp"
    - dependency-name: "Microsoft.CodeAnalysis.CSharp.Workspaces"
    # Avoids dependabot to create PR's to update wildcard majors as the project files target a specific major of these packages
    - dependency-name: "NServiceBus"
    - dependency-name: "NServiceBus.AcceptanceTesting"
    - dependency-name: "NServiceBus.SqlServer"
    - dependency-name: "NServiceBus.Transport.SqlServer"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 1000
